[package]
name = "aws-rust"
version = "0.1.0"
authors = ["ozbe <1372945+ozbe@users.noreply.github.com>"]
edition = "2018"

[dependencies]
aws_lambda_events = "0.3.0"
lambda_runtime = "0.2.1"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"