service: demo
provider:
  name: aws
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
plugins:
  - serverless-iam-roles-per-function
  - serverless-rust
package:
  individually: true
functions:
  addNote:
    handler: aws-rust-text-analysis-via-sns-post-processing.add_note
    events:
      - http:
          path: notes
          method: post
          cors: true
    environment:
      RUST_LOG: ${env:RUST_LOG}
  analyzeNote:
    handler: aws-rust-text-analysis-via-sns-post-processing.analyze_note
    events:
      - sns: analyzeNote
    environment:
      RUST_LOG: ${env:RUST_LOG}